In [2]:
import pandas as pd
import numpy as np

movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")
movies.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [3]:
credits.head(3)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [9]:
pd.set_option("display.max_column",24)

In [21]:
data = pd.merge(left = movies,right = credits,on = 'title')
data.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [22]:
data["release_date"] = pd.to_datetime(data["release_date"])

In [28]:
data.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew,Year
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2009.0
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",2007.0

In [27]:
data["Year"] = data["release_date"].dt.year

In [31]:
# Necessary features which will be helpfull to create grouped features based on which recommendation will be created:
cols = ['title','genres','id','keywords','overview','Year',"cast","crew"]
data = data[cols]
data.head(3)

,title,genres,id,keywords,overview,Year,cast,crew
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",2009.0,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",2007.0,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,2015.0,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [33]:
data = data.dropna()

In [41]:
data.head(2)

,title,genres,id,keywords,overview,Year,cast,crew
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",2009,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",2007,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [37]:
data["Year"] = data["Year"].astype("int")

In [40]:
data["Year"] = data["Year"].astype("str")

In [43]:
# Preprocessing the final dataset:
data.duplicated().sum()

0

In [57]:
data.iloc[18]["genres"]

'[{"id": 28, "name": "Action"}, {"id": 35, "name": "Comedy"}, {"id": 878, "name": "Science Fiction"}]'

In [61]:
import ast
def convert(obj):
    genres = []
    arr = ast.literal_eval(obj)
    for i in arr:
        genres.append(i["name"])
    return genres

data["genres"] = data["genres"].apply(convert)

In [76]:
def convert_cast_crew(obj):
    lst = []
    c = 0
    arr = ast.literal_eval(obj)
    for i in arr:
        if c != 3:
            lst.append(i["name"])
            c += 1
        else:
            break
    return lst

In [88]:
# Only obtain directors
def convert_crew(obj):
    lst = []
    c = 0
    arr = ast.literal_eval(obj)
    for i in arr:
        if i["job"] == "Director":
            lst.append(i["name"])
    return lst

In [90]:
data.head(2)

,title,genres,id,keywords,overview,Year,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",2009,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",2007,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]

In [64]:
data["keywords"] = data["keywords"].apply(convert)

In [79]:
data["cast"] = data["cast"].apply(convert_cast_crew)

In [89]:
data["crew"] = data["crew"].apply(convert_crew)

In [93]:
data["overview"] = data["overview"].apply(lambda x : x.split())

In [102]:
data.head(2)

,title,genres,id,keywords,overview,Year,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",[2009],"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",[2007],"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]

In [96]:
data["Year"] = data["Year"].apply(lambda x:x.split())

In [101]:
data["cast"] = data["cast"].apply(lambda x:[i.replace(" ","") for i in x])
data["overview"] = data["overview"].apply(lambda x:[i.replace(" ","") for i in x])
data["crew"] = data["crew"].apply(lambda x:[i.replace(" ","") for i in x])
data["keywords"] = data["keywords"].apply(lambda x:[i.replace(" ","") for i in x])
data["genres"] = data["genres"].apply(lambda x:[i.replace(" ","") for i in x])

In [103]:
data.head(2)

,title,genres,id,keywords,overview,Year,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",[2009],"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",[2007],"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]

In [108]:
data["tags"] = data["overview"] + data["genres"] + data["keywords"] + data["cast"] + data["crew"] + data["Year"]

In [109]:
final = data[["id","title","tags"]]
final.head()

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [116]:
final["tags"] = final["tags"].apply(lambda x:" ".join(x))

<ipython-input-116-09afa978dd6d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final["tags"] = final["tags"].apply(lambda x:" ".join(x))

In [128]:
final.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [15]:
final.to_csv("final_movies.csv",index = False)

In [127]:
final["tags"] = final["tags"].str.lower()

<ipython-input-127-209e32b2cc18>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final["tags"] = final["tags"].str.lower()

In [4]:
# Text vectorization on the tags:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words = 'english',max_features = 5000)

In [5]:
# Matrix of movies vs features:
vectors = cv.fit_transform(final["tags"]).toarray()

In [144]:
vectors[2]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [159]:
# Which words are frequently occuring in the tags:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1937',
 '1940',
 '1944',
 '1945',
 '1950',
 '1950s',
 '1955',
 '1959',
 '1960',
 '1960s',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attempttoescap',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakup',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commit',
 'common',
 'commun',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 ...]

In [147]:
import nltk

In [155]:
# Applying stemming operation on the top of tags column:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def stemming(text):
    lst = []  
    for i in text.split():
        lst.append(ps.stem(i))
    res = " ".join(lst)
    return res

final["tags"] = final["tags"].apply(stemming)

<ipython-input-155-5f0dfe347987>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final["tags"] = final["tags"].apply(stemming)

In [160]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [6]:
# Computing cosine similarity:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [7]:
# Similarity between first movie and all 4806 movies:
sorted(list(enumerate(similarity[0])),reverse = True,key = lambda x : x[1])

[(0, 1.0000000000000002),
 (1216, 0.27921779664372753),
 (2409, 0.26257545381445874),
 (3730, 0.2506402059138015),
 (507, 0.25016291953504993),
 (539, 0.24359938288234498),
 (582, 0.2396974985022249),
 (1204, 0.23870495801314426),
 (778, 0.22645540682891918),
 (4048, 0.22489899383695006),
 (61, 0.22417941532712204),
 (1194, 0.22417941532712204),
 (1920, 0.21977383072747692),
 (1089, 0.21618989813247),
 (2786, 0.21182963643408081),
 (322, 0.2051282051282051),
 (172, 0.20483662259967567),
 (972, 0.2046468711716401),
 (2333, 0.20180183819889372),
 (3608, 0.19861453057473932),
 (260, 0.19814848097530424),
 (931, 0.19814848097530424),
 (74, 0.19795764159656265),
 (151, 0.19611613513818407),
 (4192, 0.19611613513818407),
 (1444, 0.19418390934515434),
 (3675, 0.19312181983410703),
 (47, 0.19277164398874672),
 (577, 0.1922322627333814),
 (973, 0.19223226273338134),
 (2971, 0.18871283902409933),
 (4010, 0.18871283902409933),
 (305, 0.18762218965128746),
 (942, 0.18685673434682065),
 (4, 0.1849000654084097),
 (495, 0.1849000654084097),
 (1201, 0.1849000654084097),
 (27, 0.1845207828235642),
 (67, 0.18427434427242975),
 (94, 0.1815682598006407),
 (1275, 0.1815682598006407),
 (3327, 0.17902871850985821),
 (1329, 0.17841031003501576),
 (83, 0.17596234808583347),
 (3999, 0.1754116038614058),
 (1071, 0.17505471314812435),
 (2999, 0.17471413945365305),
 (168, 0.17295817388759027),
 (184, 0.17295817388759027),
 (220, 0.17255919256291524),
 (4336, 0.17093520167692652),
 (2204, 0.1709352016769265),
 (1321, 0.1706971854997297),
 (300, 0.16898159235484367),
 (36, 0.167093470609201),
 (3538, 0.167093470609201),
 (373, 0.16694514082354447),
 (3162, 0.1667752796900333),
 (1982, 0.16477051091432687),
 (529, 0.16349964255346808),
 (1831, 0.16349964255346808),
 (476, 0.1634301126151534),
 (661, 0.16269036695641684),
 (91, 0.16239958858823),
 (41, 0.1617875572323585),
 (1396, 0.1613940087116806),
 (150, 0.1611258466588724),
 (4405, 0.16012815380508713),
 (1537, 0.1585187847802434),
 (342, 0.15818713475337637),
 (595, 0.15695698526580623),
 (1560, 0.15585730003983933),
 (31, 0.15408338784034142),
 (2515, 0.15408338784034142),
 (1178, 0.15384615384615383),
 (158, 0.15253477177414312),
 (1479, 0.15253477177414312),
 (149, 0.15202972471705734),
 (187, 0.15191090506255),
 (2731, 0.1513068831672006),
 (838, 0.15097027121927944),
 (26, 0.1500468969841066),
 (1004, 0.14867525836251314),
 (754, 0.14824986333222023),
 (311, 0.14651588715165131),
 (111, 0.1465158871516513),
 (1344, 0.1465158871516513),
 (1383, 0.1465158871516513),
 (3628, 0.1465158871516513),
 (1274, 0.14617633655117152),
 (1658, 0.14617633655117152),
 (513, 0.14484136487558028),
 (122, 0.1437993271357627),
 (2075, 0.1437993271357627),
 (2760, 0.1435161644183277),
 (7, 0.14322297480788657),
 (52, 0.14322297480788657),
 (127, 0.14322297480788657),
 (108, 0.1416576493949657),
 (1297, 0.1416576493949657),
 (579, 0.14153462926807447),
 (581, 0.14153462926807445),
 (1355, 0.1401425507601155),
 (1938, 0.1401425507601155),
 (466, 0.13977131156292244),
 (275, 0.13937366833451514),
 (294, 0.13937366833451514),
 (3354, 0.13937366833451514),
 (1056, 0.1386750490563073),
 (1273, 0.1386750490563073),
 (121, 0.1373087590952724),
 (413, 0.1373087590952724),
 (461, 0.1373087590952724),
 (568, 0.1373087590952724),
 (95, 0.13725270326150324),
 (17, 0.13693937303317935),
 (56, 0.13655774839978377),
 (490, 0.13655774839978377),
 (1488, 0.13655774839978377),
 (1965, 0.13592873654160803),
 (4538, 0.1358732440973515),
 (46, 0.13533299049019168),
 (3409, 0.13533299049019168),
 (249, 0.13355611265883557),
 (1327, 0.13355611265883557),
 (3781, 0.13355611265883557),
 (72, 0.13344012817090595),
 (859, 0.13344012817090595),
 (2169, 0.13344012817090595),
 (1322, 0.1320989873168695),
 (843, 0.1316245316231641),
 (1808, 0.1316245316231641),
 (2496, 0.1316245316231641),
 (505, 0.1307440900921227),
 (668, 0.1307440900921227),
 (935, 0.1307440900921227),
 (3982, 0.1307440900921227),
 (502, 0.13074409009212268),
 (777, 0.13074409009212268),
 (126, 0.12988108336653278),
 (937, 0.12988108336653278),
 (2133, 0.1283881477532739),
 (4348, 0.1283881477532739),
 (131, 0.1282051282051282),
 (4079, 0.1282051282051282),
 (35, 0.12810252304406972),
 (1373, 0.12810252304406972),
 (2378, 0.12810252304406972),
 (2584, 0.12810252304406972),
 (1015, 0.12659242088545833),
 (2181, 0.12659242088545833),
 (3622, 0.12659242088545833),
 (2873, 0.126155140059354),
 (134, 0.12561485860426555),
 (368, 0.12561485860426555),
 (1774, 0.12561485860426555),
 (14, 0.12503908082008883),
 (138, 0.12503908082008883),
 (1086, 0.12503908082008883),
 (2686, 0.12503908082008883),
 (4230, 0.12503908082008883),
 (369, 0.1235415527768502),
 (1294, 0.1235415527768502),
 (2450, 0.1235415527768502),
 (487, 0.12326671027227314),
 (773, 0.12326671027227314),
 (1096, 0.12326671027227314),
 (2970, 0.12326671027227314),
 (1741, 0.12301385521570944),
 (166, 0.12209657262637608),
 (102, 0.12201777521731262),
 (483, 0.12104550653376048),
 (1158, 0.12104550653376048),
 (84, 0.12104550653376046),
 (1878, 0.12009611535381536),
 (2480, 0.12009611535381534),
 (3978, 0.12009611535381534),
 (438, 0.11935247900657214),
 (557, 0.11935247900657214),
 (898, 0.11935247900657214),
 (1299, 0.11935247900657214),
 (208, 0.11894020669001051),
 (2652, 0.11894020669001051),
 (3376, 0.11894020669001051),
 (3736, 0.11894020669001051),
 (139, 0.1182624791978165),
 (1002, 0.11737660545701087),
 (68, 0.11694106924093722),
 (356, 0.11694106924093722),
 (781, 0.11694106924093722),
 (549, 0.11678545896676293),
 (870, 0.11678545896676293),
 (900, 0.11678545896676293),
 (3235, 0.11678545896676293),
 (1664, 0.11651034560709261),
 (2674, 0.11651034560709261),
 (3083, 0.11651034560709261),
 (1047, 0.11503946170861017),
 (1833, 0.11503946170861017),
 (2060, 0.11503946170861017),
 (2741, 0.11503946170861017),
 (4672, 0.11503946170861017),
 (160, 0.11500161355436697),
 (182, 0.11437725271791938),
 (278, 0.11437725271791938),
 (1617, 0.11437725271791938),
 (2284, 0.11437725271791938),
 (589, 0.114022293537793),
 (3212, 0.11357879791108),
 (1673, 0.11322770341445959),
 (1715, 0.11322770341445959),
 (2331, 0.11322770341445959),
 (2789, 0.11322770341445959),
 (3721, 0.11322770341445959),
 (4000, 0.11322770341445959),
 (454, 0.11322770341445958),
 (1497, 0.11322770341445958),
 (2547, 0.11322770341445958),
 (28, 0.11322770341445956),
 (422, 0.11322770341445956),
 (678, 0.11322770341445956),
 (432, 0.11211213233271874),
 (997, 0.11211213233271873),
 (1220, 0.11211213233271873),
 (85, 0.11208970766356102),
 (236, 0.11149893466761211),
 (1301, 0.11149893466761211),
 (536, 0.11102889792108189),
 (43, 0.11102889792108188),
 (1418, 0.11102889792108188),
 (889, 0.1104452707417832),
 (189, 0.11020775375559674),
 (256, 0.11020775375559674),
 (3147, 0.11020775375559674),
 (1512, 0.10997646755364593),
 (420, 0.10997646755364592),
 (2372, 0.10997646755364592),
 (50, 0.10984700727621793),
 (1616, 0.10984700727621793),
 (229, 0.10948978029027179),
 (3309, 0.10895340841010223),
 (206, 0.10878565864408421),
 (238, 0.10878565864408421),
 (87, 0.10826639239215334),
 (232, 0.10826639239215334),
 (4468, 0.10826639239215334),
 (1574, 0.108094949066235),
 (123, 0.10795837927188262),
 (228, 0.10795837927188262),
 (1783, 0.10795837927188262),
 (81, 0.10741723110591493),
 (808, 0.10741723110591492),
 (1348, 0.10741723110591492),
 (692, 0.10699012312772824),
 (307, 0.10687334289668038),
 (21, 0.10675210253672475),
 (449, 0.10675210253672475),
 (1031, 0.10675210253672475),
 (1945, 0.10675210253672475),
 (3008, 0.10675210253672475),
 (3428, 0.10675210253672475),
 (5, 0.10604746049596296),
 (740, 0.10604746049596296),
 (3093, 0.10604746049596296),
 (3630, 0.10604746049596296),
 (306, 0.10529962529853128),
 (472, 0.10529962529853128),
 (786, 0.10529962529853128),
 (3498, 0.10529962529853128),
 (4656, 0.10529962529853128),
 (572, 0.105129283382795),
 (200, 0.10482848367219183),
 (627, 0.10482848367219183),
 (653, 0.10482848367219183),
 (939, 0.10482848367219183),
 (1524, 0.10482848367219183),
 (1575, 0.10482848367219183),
 (2317, 0.10482848367219183),
 (3155, 0.10482848367219183),
 (170, 0.10423454980627081),
 (262, 0.10423454980627081),
 (332, 0.10390486669322622),
 (1237, 0.10390486669322622),
 (1269, 0.10390486669322622),
 (467, 0.10336227882434038),
 (541, 0.10336227882434038),
 (1496, 0.10336227882434038),
 (2072, 0.10256410256410256),
 (3340, 0.10256410256410256),
 (2498, 0.1025115460130912),
 (233, 0.10241831129983783),
 (1166, 0.10241831129983783),
 (1501, 0.10241831129983783),
 (1745, 0.10241831129983783),
 (2161, 0.10241831129983783),
 (2634, 0.10241831129983783),
 (3716, 0.10241831129983783),
 (4135, 0.10241831129983783),
 (654, 0.10168147934776052),
 (2439, 0.10168147934776052),
 (75, 0.10127393670836667),
 (223, 0.10127393670836667),
 (687, 0.10127393670836667),
 (814, 0.10127393670836667),
 (922, 0.10127393670836667),
 (1195, 0.10127393670836667),
 (1771, 0.10127393670836667),
 (2148, 0.10127393670836667),
 (2817, 0.10127393670836667),
 (4097, 0.10127393670836667),
 (4623, 0.10127393670836667),
 (4776, 0.10127393670836667),
 (295, 0.10127393670836665),
 (1455, 0.10087125544480038),
 (105, 0.10016708449412667),
 (624, 0.10016708449412667),
 (2323, 0.10016708449412667),
 (2456, 0.10016708449412667),
 (2521, 0.10016708449412667),
 (3055, 0.10016708449412667),
 (3621, 0.10016708449412667),
 (3839, 0.10016708449412667),
 (2106, 0.10008009612817946),
 (10, 0.10003126465607107),
 (1082, 0.10003126465607107),
 (3152, 0.10003126465607107),
 (3755, 0.10003126465607107),
 (3874, 0.10003126465607107),
 (3441, 0.09930726528736966),
 (508, 0.09883324222148016),
 (1037, 0.09883324222148016),
 (1614, 0.09883324222148016),
 (2247, 0.09883324222148016),
 (1405, 0.09855206599818042),
 (1439, 0.09855206599818042),
 (263, 0.09805806756909202),
 (325, 0.09805806756909202),
 (2762, 0.09805806756909202),
 (3663, 0.09805806756909202),
 (3954, 0.09805806756909202),
 (2099, 0.09781383788084239),
 (312, 0.09767725810110087),
 (330, 0.09767725810110087),
 (643, 0.09767725810110087),
 (988, 0.09767725810110087),
 (2163, 0.09767725810110087),
 (363, 0.09709195467257717),
 (491, 0.09709195467257717),
 (266, 0.09656090991705352),
 (445, 0.09656090991705352),
 (510, 0.09656090991705352),
 (3285, 0.09656090991705352),
 (3620, 0.09656090991705352),
 (3634, 0.09656090991705352),
 (3783, 0.09656090991705352),
 (3935, 0.09656090991705352),
 (1775, 0.09638582199437336),
 (157, 0.09607689228305229),
 (319, 0.09607689228305229),
 (715, 0.09607689228305229),
 (1077, 0.09607689228305229),
 (1171, 0.09607689228305229),
 (1280, 0.09607689228305229),
 (1884, 0.09607689228305229),
 (2053, 0.09607689228305229),
 (4018, 0.09607689228305229),
 (4198, 0.09607689228305229),
 (4490, 0.09607689228305229),
 (230, 0.0956948752938691),
 (410, 0.09548198320525772),
 (480, 0.09548198320525772),
 (535, 0.09548198320525772),
 (1109, 0.09548198320525772),
 (1401, 0.09548198320525772),
 (1623, 0.09548198320525772),
 (1823, 0.09548198320525772),
 (2253, 0.09548198320525772),
 (3022, 0.09548198320525772),
 (9, 0.09443843292997713),
 (334, 0.09443843292997713),
 (2241, 0.09443843292997713),
 (33, 0.09421114395319916),
 (148, 0.09421114395319916),
 (1156, 0.09421114395319916),
 (1727, 0.09421114395319916),
 (1942, 0.09421114395319916),
 (2715, 0.09421114395319916),
 (4203, 0.09421114395319916),
 (4256, 0.09421114395319916),
 (4403, 0.09421114395319916),
 (4472, 0.09421114395319916),
 (4545, 0.09370791409872918),
 (76, 0.09342836717341034),
 (371, 0.09342836717341034),
 (412, 0.09342836717341034),
 (2556, 0.09342836717341034),
 (18, 0.0930725988812425),
 (11, 0.09245003270420486),
 (587, 0.09245003270420486),
 (674, 0.09245003270420486),
 (2592, 0.09245003270420486),
 (3423, 0.09245003270420486),
 (3614, 0.09245003270420486),
 (348, 0.09245003270420485),
 (362, 0.09245003270420485),
 (791, 0.09245003270420485),
 (878, 0.09245003270420485),
 (1721, 0.09245003270420485),
 (2562, 0.09245003270420485),
 (2787, 0.09245003270420485),
 (1357, 0.0915018021743355),
 (1692, 0.0915018021743355),
 (1701, 0.0915018021743355),
 (2488, 0.0915018021743355),
 (2650, 0.0915018021743355),
 (2820, 0.0915018021743355),
 (3407, 0.0915018021743355),
 (3485, 0.0915018021743355),
 (301, 0.09124148357522649),
 (660, 0.09078412990032037),
 (920, 0.09078412990032037),
 (1474, 0.09078412990032037),
 (1573, 0.09078412990032037),
 (1686, 0.09078412990032037),
 (1950, 0.09078412990032037),
 (2396, 0.09078412990032037),
 (3537, 0.09078412990032037),
 (4331, 0.09078412990032037),
 (129, 0.09058216273156766),
 (243, 0.09058216273156766),
 (279, 0.09058216273156766),
 (473, 0.09058216273156766),
 (596, 0.09058216273156766),
 (813, 0.09058216273156766),
 (1446, 0.09058216273156766),
 (2527, 0.09058216273156766),
 (239, 0.0900791242218625),
 (785, 0.0900791242218625),
 (799, 0.0900791242218625),
 (2570, 0.0895143592549291),
 (219, 0.08920515501750789),
 (244, 0.08920515501750789),
 (511, 0.08920515501750789),
 (980, 0.08920515501750789),
 (1756, 0.08920515501750789),
 (2093, 0.08920515501750789),
 (2645, 0.08920515501750789),
 (2651, 0.08920515501750789),
 (59, 0.08896008544727063),
 (602, 0.0888231183368655),
 (1233, 0.0888231183368655),
 (1276, 0.0888231183368655),
 (1846, 0.0888231183368655),
 (3462, 0.0888231183368655),
 (3720, 0.0888231183368655),
 (3881, 0.0888231183368655),
 (4353, 0.0888231183368655),
 (4502, 0.0888231183368655),
 (274, 0.08833906504195108),
 (331, 0.08798117404291673),
 (2363, 0.08798117404291673),
 (3389, 0.08798117404291673),
 (4343, 0.08798117404291673),
 (12, 0.08770580193070292),
 (88, 0.08770580193070292),
 (167, 0.08770580193070292),
 (400, 0.08770580193070292),
 (1306, 0.08770580193070292),
 (1480, 0.08770580193070292),
 (2015, 0.08770580193070292),
 (2251, 0.08770580193070292),
 (2957, 0.08770580193070292),
 (2115, 0.08735706972682653),
 (1906, 0.08716272672808179),
 (2713, 0.08716272672808179),
 (2740, 0.08716272672808179),
 (63, 0.0863667034175061),
 (169, 0.0863667034175061),
 (270, 0.0863667034175061),
 (618, 0.0863667034175061),
 (752, 0.0863667034175061),
 (2109, 0.0863667034175061),
 (3553, 0.0863667034175061),
 (8, 0.08627959628145762),
 (292, 0.08627959628145762),
 (564, 0.08627959628145762),
 (1027, 0.08627959628145762),
 (2660, 0.08627959628145762),
 (2868, 0.08627959628145762),
 (3322, 0.08627959628145762),
 (199, 0.08559209850218259),
 (1019, 0.08559209850218259),
 (1832, 0.08559209850218259),
 (2796, 0.08559209850218259),
 (2856, 0.08559209850218259),
 (3443, 0.08559209850218259),
 (3885, 0.08559209850218259),
 (2448, 0.08534859274986485),
 (23, 0.08492077756084468),
 (141, 0.08492077756084468),
 (389, 0.08492077756084468),
 (745, 0.08492077756084468),
 (794, 0.08492077756084468),
 (960, 0.08492077756084468),
 (1249, 0.08492077756084468),
 (1259, 0.08492077756084468),
 (3448, 0.08492077756084468),
 (3449, 0.08492077756084468),
 (4780, 0.08492077756084468),
 (479, 0.08486775178136235),
 (143, 0.08483796839677037),
 (827, 0.08483796839677037),
 (3556, 0.08483796839677037),
 (234, 0.084103426706236),
 (2354, 0.084103426706236),
 (2, 0.08362420100070908),
 (142, 0.08362420100070908),
 (457, 0.08362420100070908),
 (775, 0.08362420100070908),
 (1378, 0.08362420100070908),
 (2583, 0.08362420100070908),
 (3135, 0.08362420100070908),
 (4753, 0.08362420100070908),
 (32, 0.08338763984501665),
 (217, 0.08338763984501665),
 (2968, 0.08338763984501665),
 (48, 0.0826898230594723),
 (190, 0.0826898230594723),
 (1305, 0.0826898230594723),
 (1530, 0.0826898230594723),
 (1639, 0.0826898230594723),
 (2880, 0.0826898230594723),
 (4516, 0.0826898230594723),
 (4586, 0.0826898230594723),
 (894, 0.08238525545716345),
 (1097, 0.08238525545716345),
 (1142, 0.08238525545716345),
 (1589, 0.08238525545716345),
 (2304, 0.08238525545716345),
 (4559, 0.08238525545716345),
 (4774, 0.08238525545716345),
 (963, 0.08200923681047297),
 (2386, 0.0817150563075767),
 (19, 0.08134518347820842),
 (403, 0.08134518347820842),
 (3905, 0.08134518347820842),
 (1, 0.081199794294115),
 (152, 0.081199794294115),
 (203, 0.081199794294115),
 (315, 0.081199794294115),
 (547, 0.081199794294115),
 (1303, 0.081199794294115),
 (1688, 0.081199794294115),
 (2128, 0.081199794294115),
 (3137, 0.081199794294115),
 (3304, 0.081199794294115),
 (3470, 0.081199794294115),
 (2203, 0.0806970043558403),
 (39, 0.08006407690254357),
 (45, 0.08006407690254357),
 (62, 0.08006407690254357),
 (227, 0.08006407690254357),
 (341, 0.08006407690254357),
 (381, 0.08006407690254357),
 (501, 0.08006407690254357),
 (534, 0.08006407690254357),
 (626, 0.08006407690254357),
 (787, 0.08006407690254357),
 (1207, 0.08006407690254357),
 (1698, 0.08006407690254357),
 (1749, 0.08006407690254357),
 (2167, 0.08006407690254357),
 (2644, 0.08006407690254357),
 (2661, 0.08006407690254357),
 (3140, 0.08006407690254357),
 (3180, 0.08006407690254357),
 (3218, 0.08006407690254357),
 (3301, 0.08006407690254357),
 (3386, 0.08006407690254357),
 (4605, 0.08006407690254357),
 (4736, 0.08006407690254357),
 (4788, 0.08006407690254357),
 (38, 0.07944581222989573),
 (812, 0.07944581222989573),
 (242, 0.07897471897389846),
 (245, 0.07897471897389846),
 (899, 0.07897471897389846),
 (901, 0.07897471897389846),
 (1519, 0.07897471897389846),
 (2865, 0.07897471897389846),
 (3764, 0.07897471897389846),
 (3926, 0.07897471897389846),
 (4625, 0.07897471897389846),
 (51, 0.07884165279854434),
 (222, 0.07884165279854434),
 (2792, 0.07884165279854434),
 (486, 0.07850928662766597),
 (103, 0.0782510703046739),
 (1534, 0.0782510703046739),
 (16, 0.07792865001991967),
 (164, 0.07792865001991967),
 (854, 0.07792865001991967),
 (1325, 0.07792865001991967),
 (1747, 0.07792865001991967),
 (2683, 0.07792865001991967),
 (3233, 0.07792865001991967),
 (3816, 0.07792865001991967),
 (3851, 0.07792865001991967),
 (4316, 0.07792865001991967),
 (584, 0.07767356373806174),
 (866, 0.07767356373806174),
 (1007, 0.07767356373806174),
 (1898, 0.07767356373806174),
 (2339, 0.07767356373806174),
 (2353, 0.07767356373806174),
 (2671, 0.07767356373806174),
 (2877, 0.07767356373806174),
 (2891, 0.07767356373806174),
 (4492, 0.07767356373806174),
 (4506, 0.07767356373806174),
 (4653, 0.07767356373806174),
 (193, 0.07740086460344697),
 (153, 0.07710865759549869),
 (1828, 0.07710865759549869),
 (1926, 0.07710865759549869),
 (37, 0.07692307692307693),
 (241, 0.07692307692307693),
 (329, 0.07692307692307693),
 (402, 0.07692307692307693),
 (1080, 0.07692307692307693),
 (1161, 0.07692307692307693),
 (2295, 0.07692307692307693),
 (286, 0.07655590023509527),
 (1659, 0.07655590023509527),
 (1924, 0.07601486235852867),
 (3560, 0.07601486235852867),
 (174, 0.075955452531275),
 (397, 0.075955452531275),
 (632, 0.075955452531275),
 (1113, 0.075955452531275),
 (2938, 0.075955452531275),
 (3028, 0.075955452531275),
 (3091, 0.075955452531275),
 (3102, 0.075955452531275),
 (3164, 0.075955452531275),
 (4341, 0.075955452531275),
 (776, 0.07548513560963972),
 (1045, 0.07548513560963972),
 (1282, 0.07548513560963972),
 (3528, 0.07548513560963972),
 (3728, 0.07548513560963972),
 (3832, 0.07548513560963972),
 (4279, 0.07548513560963972),
 (4400, 0.07548513560963972),
 (4567, 0.07548513560963972),
 (4770, 0.07548513560963972),
 (40, 0.07502344849205331),
 (96, 0.07502344849205331),
 (101, 0.07502344849205331),
 (112, 0.07502344849205331),
 (207, 0.07502344849205331),
 (737, 0.07502344849205331),
 (1289, 0.07502344849205331),
 (2219, 0.07502344849205331),
 (4268, 0.07502344849205331),
 (125, 0.07479575920067656),
 (246, 0.074458079104994),
 (70, 0.07412493166611012),
 (82, 0.07412493166611012),
 (163, 0.07412493166611012),
 (235, 0.07412493166611012),
 (349, 0.07412493166611012),
 (365, 0.07412493166611012),
 (492, 0.07412493166611012),
 (540, 0.07412493166611012),
 (1290, 0.07412493166611012),
 (1523, 0.07412493166611012),
 (2449, 0.07412493166611012),
 (2902, 0.07412493166611012),
 (2916, 0.07412493166611012),
 (4205, 0.07412493166611012),
 (4557, 0.07412493166611012),
 (3331, 0.07401926528072125),
 (2005, 0.07396002616336388),
 (850, 0.0734718358370645),

In [8]:
def get_names_of_movies(index):
    return final.iloc[index]["title"]

In [11]:
# Recommend movies:
def Recommend(movie):
    movie_index = final[final["title"] == movie].index[0]
    distances = similarity[movie_index]
    ans = sorted(list(enumerate(distances)),reverse = True,key = lambda x : x[1])
 
    name = []
    for i in ans[:11]:
        name.append(get_names_of_movies(i[0]))
    name.pop(0)
    return name

# Top 10 Recommended Movies:
Recommend("The Amazing Spider-Man")

['Krrish',
 '1982',
 'The Beastmaster',
 'Flying By',
 "Should've Been Romeo",
 'Copying Beethoven',
 'All Is Lost',
 'Micmacs',
 'After Earth',
 'The Diving Bell and the Butterfly']

In [179]:
final.iloc[11]["title"]

'Quantum of Solace'

In [190]:
final.to_csv("Final_Movies.csv",index = False)

In [192]:
list(final["title"])

['Avatar',
 "Pirates of the Caribbean: At World's End",
 'Spectre',
 'The Dark Knight Rises',
 'John Carter',
 'Spider-Man 3',
 'Tangled',
 'Avengers: Age of Ultron',
 'Harry Potter and the Half-Blood Prince',
 'Batman v Superman: Dawn of Justice',
 'Superman Returns',
 'Quantum of Solace',
 "Pirates of the Caribbean: Dead Man's Chest",
 'The Lone Ranger',
 'Man of Steel',
 'The Chronicles of Narnia: Prince Caspian',
 'The Avengers',
 'Pirates of the Caribbean: On Stranger Tides',
 'Men in Black 3',
 'The Hobbit: The Battle of the Five Armies',
 'The Amazing Spider-Man',
 'Robin Hood',
 'The Hobbit: The Desolation of Smaug',
 'The Golden Compass',
 'King Kong',
 'Titanic',
 'Captain America: Civil War',
 'Battleship',
 'Jurassic World',
 'Skyfall',
 'Spider-Man 2',
 'Iron Man 3',
 'Alice in Wonderland',
 'X-Men: The Last Stand',
 'Monsters University',
 'Transformers: Revenge of the Fallen',
 'Transformers: Age of Extinction',
 'Oz: The Great and Powerful',
 'The Amazing Spider-Man 2',
 'TRON: Legacy',
 'Cars 2',
 'Green Lantern',
 'Toy Story 3',
 'Terminator Salvation',
 'Furious 7',
 'World War Z',
 'X-Men: Days of Future Past',
 'Star Trek Into Darkness',
 'Jack the Giant Slayer',
 'The Great Gatsby',
 'Prince of Persia: The Sands of Time',
 'Pacific Rim',
 'Transformers: Dark of the Moon',
 'Indiana Jones and the Kingdom of the Crystal Skull',
 'The Good Dinosaur',
 'Brave',
 'Star Trek Beyond',
 'WALL·E',
 'Rush Hour 3',
 '2012',
 'A Christmas Carol',
 'Jupiter Ascending',
 'The Legend of Tarzan',
 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
 'X-Men: Apocalypse',
 'The Dark Knight',
 'Up',
 'Monsters vs Aliens',
 'Iron Man',
 'Hugo',
 'Wild Wild West',
 'The Mummy: Tomb of the Dragon Emperor',
 'Suicide Squad',
 'Evan Almighty',
 'Edge of Tomorrow',
 'Waterworld',
 'G.I. Joe: The Rise of Cobra',
 'Inside Out',
 'The Jungle Book',
 'Iron Man 2',
 'Snow White and the Huntsman',
 'Maleficent',
 'Dawn of the Planet of the Apes',
 'The Lovers',
 '47 Ronin',
 'Captain America: The Winter Soldier',
 'Shrek Forever After',
 'Tomorrowland',
 'Big Hero 6',
 'Wreck-It Ralph',
 'The Polar Express',
 'Independence Day: Resurgence',
 'How to Train Your Dragon',
 'Terminator 3: Rise of the Machines',
 'Guardians of the Galaxy',
 'Interstellar',
 'Inception',
 'Shin Godzilla',
 'The Hobbit: An Unexpected Journey',
 'The Fast and the Furious',
 'The Curious Case of Benjamin Button',
 'X-Men: First Class',
 'The Hunger Games: Mockingjay - Part 2',
 "The Sorcerer's Apprentice",
 'Poseidon',
 'Alice Through the Looking Glass',
 'Shrek the Third',
 'Warcraft',
 'Terminator Genisys',
 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
 'Pearl Harbor',
 'Transformers',
 'Alexander',
 'Harry Potter and the Order of the Phoenix',
 'Harry Potter and the Goblet of Fire',
 'Hancock',
 'I Am Legend',
 'Charlie and the Chocolate Factory',
 'Ratatouille',
 'Batman Begins',
 'Madagascar: Escape 2 Africa',
 'Night at the Museum: Battle of the Smithsonian',
 'X-Men Origins: Wolverine',
 'The Matrix Revolutions',
 'Frozen',
 'The Matrix Reloaded',
 'Thor: The Dark World',
 'Mad Max: Fury Road',
 'Angels & Demons',
 'Thor',
 'Bolt',
 'G-Force',
 'Wrath of the Titans',
 'Dark Shadows',
 'Mission: Impossible - Rogue Nation',
 'The Wolfman',
 'Bee Movie',
 'Kung Fu Panda 2',
 'The Last Airbender',
 'Mission: Impossible III',
 'White House Down',
 'Mars Needs Moms',
 'Flushed Away',
 'Pan',
 'Mr. Peabody & Sherman',
 'Troy',
 "Madagascar 3: Europe's Most Wanted",
 'Die Another Day',
 'Ghostbusters',
 'Armageddon',
 'Men in Black II',
 'Beowulf',
 'Kung Fu Panda 3',
 'Mission: Impossible - Ghost Protocol',
 'Rise of the Guardians',
 'Fun with Dick and Jane',
 'The Last Samurai',
 'Exodus: Gods and Kings',
 'Star Trek',
 'Spider-Man',
 'How to Train Your Dragon 2',
 'Gods of Egypt',
 'Stealth',
 'Watchmen',
 'Lethal Weapon 4',
 'Hulk',
 'G.I. Joe: Retaliation',
 'Sahara',
 'Final Fantasy: The Spirits Within',
 'Captain America: The First Avenger',
 'The World Is Not Enough',
 'Master and Commander: The Far Side of the World',
 'The Twilight Saga: Breaking Dawn - Part 2',
 'Happy Feet Two',
 'The Incredible Hulk',
 'The BFG',
 'The Revenant',
 'Turbo',
 'Rango',
 'Penguins of Madagascar',
 'The Bourne Ultimatum',
 'Kung Fu Panda',
 'Ant-Man',
 'The Hunger Games: Catching Fire',
 'Home',
 'War of the Worlds',
 'Bad Boys II',
 'Puss in Boots',
 'Salt',
 'Noah',
 'The Adventures of Tintin',
 'Harry Potter and the Prisoner of Azkaban',
 'Australia',
 'After Earth',
 'Dinosaur',
 'Night at the Museum: Secret of the Tomb',
 'Megamind',
 "Harry Potter and the Philosopher's Stone",
 'R.I.P.D.',
 'Pirates of the Caribbean: The Curse of the Black Pearl',
 'The Hunger Games: Mockingjay - Part 1',
 'The Da Vinci Code',
 'Rio 2',
 'X2',
 'Fast Five',
 'Sherlock Holmes: A Game of Shadows',
 'Clash of the Titans',
 'Total Recall',
 'The 13th Warrior',
 'The Bourne Legacy',
 'Batman & Robin',
 'How the Grinch Stole Christmas',
 'The Day After Tomorrow',
 'Mission: Impossible II',
 'The Perfect Storm',
 'Fantastic 4: Rise of the Silver Surfer',
 'Life of Pi',
 'Ghost Rider',
 'Jason Bourne',
 "Charlie's Angels: Full Throttle",
 'Prometheus',
 'Stuart Little 2',
 'Elysium',
 'The Chronicles of Riddick',
 'RoboCop',
 'Speed Racer',
 'How Do You Know',
 'Knight and Day',
 'Oblivion',
 'Star Wars: Episode III - Revenge of the Sith',
 'Star Wars: Episode II - Attack of the Clones',
 'Monsters, Inc.',
 'The Wolverine',
 'Star Wars: Episode I - The Phantom Menace',
 'The Croods',
 'Asterix at the Olympic Games',
 'Windtalkers',
 "The Huntsman: Winter's War",
 'Teenage Mutant Ninja Turtles',
 'Gravity',
 "Dante's Peak",
 'Teenage Mutant Ninja Turtles: Out of the Shadows',
 'Fantastic Four',
 'Night at the Museum',
 'San Andreas',
 'Tomorrow Never Dies',
 'The Patriot',
 "Ocean's Twelve",
 'Mr. & Mrs. Smith',
 'Insurgent',
 'The Aviator',
 "Gulliver's Travels",
 'The Green Hornet',
 '300: Rise of an Empire',
 'The Smurfs',
 'Home on the Range',
 'Allegiant',
 'Real Steel',
 'The Smurfs 2',
 'Speed 2: Cruise Control',
 "Ender's Game",
 'Live Free or Die Hard',
 'The Lord of the Rings: The Fellowship of the Ring',
 'Around the World in 80 Days',
 'Ali',
 'The Cat in the Hat',
 'I, Robot',
 'Kingdom of Heaven',
 'Stuart Little',
 'The Princess and the Frog',
 'The Martian',
 'The Island',
 'Town & Country',
 'Gone in Sixty Seconds',
 'Gladiator',
 'Minority Report',
 'Harry Potter and the Chamber of Secrets',
 'Casino Royale',
 'Planet of the Apes',
 'Terminator 2: Judgment Day',
 'Public Enemies',
 'American Gangster',
 'True Lies',
 'The Taking of Pelham 1 2 3',
 'Little Fockers',
 'The Other Guys',
 'Eraser',
 'Django Unchained',
 'The Hunchback of Notre Dame',
 "The Emperor's New Groove",
 'The Expendables 2',
 'National Treasure',
 'Eragon',
 'Where the Wild Things Are',
 'Epic',
 'The Tourist',
 'End of Days',
 'Blood Diamond',
 'The Wolf of Wall Street',
 'Batman Forever',
 'Starship Troopers',
 'Cloud Atlas',
 "Legend of the Guardians: The Owls of Ga'Hoole",
 'Catwoman',
 'Hercules',
 'Treasure Planet',
 'Land of the Lost',
 'The Expendables 3',
 'Point Break',
 'Son of the Mask',
 'In the Heart of the Sea',
 'The Adventures of Pluto Nash',
 'Green Zone',
 'The Peanuts Movie',
 'The Spanish Prisoner',
 'The Mummy Returns',
 'Gangs of New York',
 'The Flowers of War',
 "Surf's Up",
 'The Stepford Wives',
 'Black Hawk Down',
 'The Campaign',
 'The Fifth Element',
 'Sex and the City 2',
 'The Road to El Dorado',
 'Ice Age: Continental Drift',
 'Cinderella',
 'The Lovely Bones',
 'Finding Nemo',
 'The Lord of the Rings: The Return of the King',
 'The Lord of the Rings: The Two Towers',
 'Seventh Son',
 'Lara Croft: Tomb Raider',
 'Transcendence',
 'Jurassic Park III',
 'Rise of the Planet of the Apes',
 'The Spiderwick Chronicles',
 'A Good Day to Die Hard',
 'The Alamo',
 'The Incredibles',
 'Cutthroat Island',
 'Percy Jackson & the Olympians: The Lightning Thief',
 'Men in Black',
 'Toy Story 2',
 'Unstoppable',
 'Rush Hour 2',
 'What Lies Beneath',
 'Cloudy with a Chance of Meatballs',
 'Ice Age: Dawn of the Dinosaurs',
 'The Secret Life of Walter Mitty',
 "Charlie's Angels",
 'The Departed',
 'Mulan',
 'Tropic Thunder',
 'The Girl with the Dragon Tattoo',
 'Die Hard: With a Vengeance',
 'Sherlock Holmes',
 'Ben-Hur',
 'Atlantis: The Lost Empire',
 'Alvin and the Chipmunks: The Road Chip',
 'Valkyrie',
 "You Don't Mess with the Zohan",
 'Pixels',
 'A.I. Artificial Intelligence',
 'The Haunted Mansion',
 'Contact',
 'Hollow Man',
 'The Interpreter',
 'Percy Jackson: Sea of Monsters',
 'Lara Croft Tomb Raider: The Cradle of Life',
 'Now You See Me 2',
 'The Saint',
 'Spy Game',
 'Mission to Mars',
 'Rio',
 'Bicentennial Man',
 'Volcano',
 "The Devil's Own",
 'K-19: The Widowmaker',
 'Conan the Barbarian',
 'Cinderella Man',
 'The Nutcracker: The Untold Story',
 'Seabiscuit',
 'Twister',
 'Cast Away',
 'Happy Feet',
 'The Bourne Supremacy',
 'Air Force One',
 "Ocean's Eleven",
 'The Three Musketeers',
 'Hotel Transylvania',
 'Enchanted',
 'Safe House',
 '102 Dalmatians',
 'Tower Heist',
 'The Holiday',
 'Enemy of the State',
 "It's Complicated",
 "Ocean's Thirteen",
 'Open Season',
 'Divergent',
 'Enemy at the Gates',
 'The Rundown',
 'Last Action Hero',
 'Memoirs of a Geisha',
 'The Fast and the Furious: Tokyo Drift',
 'Arthur Christmas',
 'Meet Joe Black',
 'Collateral Damage',
 'All That Jazz',
 'Mirror Mirror',
 'Scott Pilgrim vs. the World',
 'The Core',
 'Nutty Professor II: The Klumps',
 'Scooby-Doo',
 'Dredd',
 'Click',
 'Creepshow',
 'Cats & Dogs 2 : The Revenge of Kitty Galore',
 'Jumper',
 'Hellboy II: The Golden Army',
 'Zodiac',
 'The 6th Day',
 'Bruce Almighty',
 'The Expendables',
 'Mission: Impossible',
 'The Hunger Games',
 'The Hangover Part II',
 'Batman Returns',
 'Over the Hedge',
 'Lilo & Stitch',
 "Charlotte's Web",
 'Deep Impact',
 'RED 2',
 'The Longest Yard',
 'Alvin and the Chipmunks: Chipwrecked',
 'Grown Ups 2',
 'Get Smart',
 "Something's Gotta Give",
 'Shutter Island',
 'Four Christmases',
 'Robots',
 'Face/Off',
 'Bedtime Stories',
 'Road to Perdition',
 'Just Go with It',
 'Con Air',
 'Eagle Eye',
 'Cold Mountain',
 'The Book of Eli',
 'Flubber',
 'The Haunting',
 'Space Jam',
 'The Pink Panther',
 'The Day the Earth Stood Still',
 'Conspiracy Theory',
 'Fury',
 'Six Days Seven Nights',
 'Yogi Bear',
 'Spirit: Stallion of the Cimarron',
 'Zookeeper',
 'Lost in Space',
 'The Manchurian Candidate',
 'Déjà Vu',
 'Hotel Transylvania 2',
 'Fantasia 2000',
 'The Time Machine',
 'Mighty Joe Young',
 'Swordfish',
 'The Legend of Zorro',
 'What Dreams May Come',
 'Little Nicky',
 'The Brothers Grimm',
 'Mars Attacks!',
 'Evolution',
 'The Edge',
 'Surrogates',
 'Thirteen Days',
 'Daylight',
 'Walking With Dinosaurs',
 'Battlefield Earth',
 'Looney Tunes: Back in Action',
 'Nine',
 'Timeline',
 'The Postman',
 'Babe: Pig in the City',
 'The Last Witch Hunter',
 'Red Planet',
 'Arthur and the Invisibles',
 'Oceans',
 'A Sound of Thunder',
 'Pompeii',
 'Top Cat Begins',
 'A Beautiful Mind',
 'The Lion King',
 'Journey 2: The Mysterious Island',
 'Cloudy with a Chance of Meatballs 2',
 'Red Dragon',
 'Hidalgo',
 'Jack and Jill',
 '2 Fast 2 Furious',
 'The Little Prince',
 'The Invasion',
 'The Adventures of Rocky & Bullwinkle',
 'The Secret Life of Pets',
 'The League of Extraordinary Gentlemen',
 'Despicable Me 2',
 'Independence Day',
 'The Lost World: Jurassic Park',
 'Madagascar',
 'Children of Men',
 'X-Men',
 'Wanted',
 'The Rock',
 'Ice Age: The Meltdown',
 '50 First Dates',
 'Hairspray',
 'Exorcist: The Beginning',
 'Inspector Gadget',
 'Now You See Me',
 'Grown Ups',
 'The Terminal',
 'Hotel for Dogs',
 'Vertical Limit',
 "Charlie Wilson's War",
 'Shark Tale',
 'Dreamgirls',
 'Be Cool',
 'Munich',
 'Tears of the Sun',
 'Killers',
 'The Man from U.N.C.L.E.',
 'Spanglish',
 'Monster House',
 'Bandits',
 'First Knight',
 'Anna and the King',
 'Immortals',
 'Hostage',
 'Titan A.E.',
 'Hollywood Homicide',
 'Soldier',
 'Carriers',
 'Monkeybone',
 'Flight of the Phoenix',
 'Unbreakable',
 'Minions',
 'Sucker Punch',
 'Snake Eyes',
 'Sphere',
 'The Angry Birds Movie',
 "Fool's Gold",
 'Funny People',
 'The Kingdom',
 'Talladega Nights: The Ballad of Ricky Bobby',
 'Dr. Dolittle 2',
 'Braveheart',
 'Jarhead',
 'The Simpsons Movie',
 'The Majestic',
 'Driven',
 'Two Brothers',
 'The Village',
 'Doctor Dolittle',
 'Signs',
 'Shrek 2',
 'Cars',
 'Runaway Bride',
 'xXx',
 'The SpongeBob Movie: Sponge Out of Water',
 'Ransom',
 'Inglourious Basterds',
 'Hook',
 'Die Hard 2',
 'S.W.A.T.',
 'Vanilla Sky',
 'Lady in the Water',
 'AVP: Alien vs. Predator',
 'Alvin and the Chipmunks: The Squeakquel',
 'We Were Soldiers',
 'Olympus Has Fallen',
 'Star Trek: Insurrection',
 'Battle: Los Angeles',
 'Big Fish',
 'Wolf',
 'War Horse',
 'The Monuments Men',
 'The Abyss',
 'Wall Street: Money Never Sleeps',
 'Dracula Untold',
 'The Siege',
 'Stardust',
 'Seven Years in Tibet',
 'The Dilemma',
 'Bad Company',
 'Doom',
 'I Spy',
 'Underworld: Awakening',
 'Rock of Ages',
 "Hart's War",
 'Killer Elite',
 'Rollerball',
 'Ballistic: Ecks vs. Sever',
 'Hard Rain',
 'Osmosis Jones',
 "Legends of Oz: Dorothy's Return",
 'Blackhat',
 'Sky Captain and the World of Tomorrow',
 'Basic Instinct 2',
 'Escape Plan',
 'The Legend of Hercules',
 'The Sum of All Fears',
 'The Twilight Saga: Eclipse',
 'The Score',
 'Despicable Me',
 'Money Train',
 'Ted 2',
 'Agora',
 'Mystery Men',
 'Hall Pass',
 'The Insider',
 'The Finest Hours',
 'Body of Lies',
 'Dinner for Schmucks',
 'Abraham Lincoln: Vampire Hunter',
 'Entrapment',
 'The X Files',
 'The Last Legion',
 'Saving Private Ryan',
 'Need for Speed',
 'What Women Want',
 'Ice Age',
 'Dreamcatcher',
 'Lincoln',
 'The Matrix',
 'Apollo 13',
 'The Santa Clause 2',
 'Les Misérables',
 "You've Got Mail",
 'Step Brothers',
 'The Mask of Zorro',
 'Due Date',
 'Unbroken',
 'Space Cowboys',
 'Cliffhanger',
 'Broken Arrow',
 'The Kid',
 'World Trade Center',
 'Mona Lisa Smile',
 'The Dictator',
 'Eyes Wide Shut',
 'Annie',
 'Focus',
 'This Means War',
 'Blade: Trinity',
 'Red Dawn',
 'Primary Colors',
 'Resident Evil: Retribution',
 'Death Race',
 'The Long Kiss Goodnight',
 'Proof of Life',
 'Zathura: A Space Adventure',
 'Fight Club',
 'We Are Marshall',
 'Hudson Hawk',
 'Lucky Numbers',
 'I, Frankenstein',
 'Oliver Twist',
 'Elektra',
 'Sin City: A Dame to Kill For',
 'Random Hearts',
 'Everest',
 'Perfume: The Story of a Murderer',
 'Austin Powers in Goldmember',
 'Astro Boy',
 'Jurassic Park',
 'Wyatt Earp',
 'Clear and Present Danger',
 'Dragon Blade',
 'Little Man',
 'U-571',
 'The American President',
 'The Love Guru',
 '3000 Miles to Graceland',
 'The Hateful Eight',
 'Blades of Glory',
 'Hop',
 '300',
 'Meet the Fockers',
 'Marley & Me',
 'The Green Mile',
 'Wild Hogs',
 'Chicken Little',
 'Gone Girl',
 'The Bourne Identity',
 'GoldenEye',
 "The General's Daughter",
 'The Truman Show',
 'The Prince of Egypt',
 'Daddy Day Care',
 '2 Guns',
 'Cats & Dogs',
 'The Italian Job',
 'Two Weeks Notice',
 'Antz',
 'Couples Retreat',
 'Days of Thunder',
 'Cheaper by the Dozen 2',
 'Maze Runner: The Scorch Trials',
 'Eat Pray Love',
 'The Family Man',
 'RED',
 'Any Given Sunday',
 'The Horse Whisperer',
 'Collateral',
 'The Scorpion King',
 'Ladder 49',
 'Jack Reacher',
 'Deep Blue Sea',
 'This Is It',
 'Contagion',
 'Kangaroo Jack',
 'Coraline',
 'The Happening',
 'Man on Fire',
 'The Shaggy Dog',
 'Starsky & Hutch',
 'Jingle All the Way',
 'Hellboy',
 'A Civil Action',
 'ParaNorman',
 'The Jackal',
 'Paycheck',
 'Up Close & Personal',
 'The Tale of Despereaux',
 'The Tuxedo',
 'Under Siege 2: Dark Territory',
 'Jack Ryan: Shadow Recruit',
 'Joy',
 'London Has Fallen',
 'Alien: Resurrection',
 'Shooter',
 'The Boxtrolls',
 'Practical Magic',
 'The Lego Movie',
 'Miss Congeniality 2: Armed and Fabulous',
 'Reign of Fire',
 'Gangster Squad',
 'Year One',
 'Invictus',
 'State of Play',
 'Duplicity',
 'My Favorite Martian',
 'The Sentinel',
 'Planet 51',
 'Star Trek: Nemesis',
 'Intolerable Cruelty',
 'Trouble with the Curve',
 'Edge of Darkness',
 'The Relic',
 'Analyze That',
 'Righteous Kill',
 'Mercury Rising',
 'The Soloist',
 'The Legend of Bagger Vance',
 'Almost Famous',
 'Garfield: A Tail of Two Kitties',
 'xXx: State of the Union',
 'Priest',
 'Sinbad: Legend of the Seven Seas',
 'Event Horizon',
 'Dragonfly',
 'The Black Dahlia',
 'Flyboys',
 'The Last Castle',
 'Supernova',
 "Winter's Tale",
 'The Mortal Instruments: City of Bones',
 'Meet Dave',
 'Dark Water',
 'Edtv',
 'Inkheart',
 'The Spirit',
 'Mortdecai',
 'In the Name of the King: A Dungeon Siege Tale',
 'Beyond Borders',
 'The Monkey King 2',
 'The Great Raid',
 'Deadpool',
 'Holy Man',
 'American Sniper',
 'Goosebumps',
 'Just Like Heaven',
 'The Flintstones in Viva Rock Vegas',
 'Rambo III',
 'Leatherheads',
 'The Ridiculous 6',
 'Did You Hear About the Morgans?',
 'The Internship',
 'Resident Evil: Afterlife',
 'Red Tails',
 "The Devil's Advocate",
 "That's My Boy",
 'DragonHeart',
 'After the Sunset',
 'Ghost Rider: Spirit of Vengeance',
 "Captain Corelli's Mandolin",
 'The Pacifier',
 'Walking Tall',
 'Forrest Gump',
 'Alvin and the Chipmunks',
 'Meet the Parents',
 'Pocahontas',
 'Superman',
 'The Nutty Professor',
 'Hitch',
 'George of the Jungle',
 'American Wedding',
 'Captain Phillips',
 'Date Night',
 'Casper',
 'The Equalizer',
 'Maid in Manhattan',
 'Crimson Tide',
 'The Pursuit of Happyness',
 'Flightplan',
 'Disclosure',
 'City of Angels',
 'Kill Bill: Vol. 1',
 'Bowfinger',
 'Kill Bill: Vol. 2',
 'Tango & Cash',
 'Death Becomes Her',
 'Shanghai Noon',
 'Executive Decision',
 "Mr. Popper's Penguins",
 'The Forbidden Kingdom',
 'Free Birds',
 'Alien³',
 'Evita',
 'Ronin',
 'The Ghost and the Darkness',
 'Paddington',
 'The Watch',
 'The Hunted',
 'Instinct',
 'Stuck on You',
 'Semi-Pro',
 'The Pirates! In an Adventure with Scientists!',
 'Changeling',
 'Chain Reaction',
 'The Fan',
 'The Phantom of the Opera',
 'Elizabeth: The Golden Age',
 'Æon Flux',
 'Gods and Generals',
 'Turbulence',
 'Imagine That',
 'Muppets Most Wanted',
 'Thunderbirds',
 'Burlesque',
 'A Very Long Engagement',
 'Lolita',
 'D-Tox',
 'Blade II',
 'Seven Pounds',
 'Bullet to the Head',
 'The Godfather: Part III',
 'Elizabethtown',
 'You, Me and Dupree',
 'Superman II',
 'Gigli',
 "All the King's Men",
 'Shaft',
 'Anastasia',
 'Moulin Rouge!',
 'Domestic Disturbance',
 'Black Mass',
 'Flags of Our Fathers',
 'Law Abiding Citizen',
 'Grindhouse',
 'Beloved',
 'Lucky You',
 'Catch Me If You Can',
 'Zero Dark Thirty',
 'The Break-Up',
 'Mamma Mia!',
 "Valentine's Day",
 'The Dukes of Hazzard',
 'The Thin Red Line',
 'The Change-Up',
 'Man on the Moon',
 'Casino',
 'From Paris with Love',
 'Bulletproof Monk',
 'Me, Myself & Irene',
 'Barnyard',
 'Deck the Halls',
 'The Twilight Saga: New Moon',
 'Shrek',
 'The Adjustment Bureau',
 'Robin Hood: Prince of Thieves',
 'Jerry Maguire',
 'Ted',
 'As Good as It Gets',
 'Patch Adams',
 'Anchorman 2: The Legend Continues',
 'Mr. Deeds',
 'Super 8',
 'Erin Brockovich',
 'How to Lose a Guy in 10 Days',
 '22 Jump Street',
 'Interview with the Vampire',
 'Yes Man',
 'Central Intelligence',
 'Stepmom',
 "Daddy's Home",
 'Into the Woods',
 'Inside Man',
 'Payback',
 'Congo',
 'We Bought a Zoo',
 'Knowing',
 'Failure to Launch',
 'The Ring Two',
 'Crazy, Stupid, Love.',
 'Garfield',
 'Christmas with the Kranks',
 'Moneyball',
 'Outbreak',
 'Non-Stop',
 'Race to Witch Mountain',
 'V for Vendetta',
 'Shanghai Knights',
 'Curious George',
 'Herbie Fully Loaded',
 "Don't Say a Word",
 'Hansel & Gretel: Witch Hunters',
 'Unfaithful',
 'I Am Number Four',
 'Syriana',
 '13 Hours: The Secret Soldiers of Benghazi',
 'The Book of Life',
 'Firewall',
 'Absolute Power',
 'G.I. Jane',
 'The Game',
 'Silent Hill',
 'The Replacements',
 'American Reunion',
 'The Negotiator',
 'Into the Storm',
 'Beverly Hills Cop III',
 'Gremlins 2: The New Batch',

In [1]:
import pandas as pd
data = pd.read_csv("Final_Movies.csv")
data.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [2]:
final = data.copy()

In [14]:
final = final[final["title"] != 'The Amazing Spider-Man']

In [ ]:
fina